site_name: current-setpoints
site_description: A library for calculating optimal current setpoints for PMSM drives
site_author: Tereza Matasova

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Usage: usage.md
  - API Reference: api.md