site_name: current-setpoints
site_description: A library for calculating optimal current setpoints in multiphase PMSM drives
site_author: Tereza Matasova

theme:
  name: readthedocs

nav:
  - Home: index.md
