from typing import Any

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.axes import Axes

from ..data import BaseMachine
from ..model import MachineData
from .plot_config import PlotConfig


def plot_grid_segments(
    data_obj: MachineData,
    title: str = "Segments Overview",
    machine: BaseMachine | None = None,
    override_torq_2d: np.ndarray | None = None,
) -> None:
    """
    Plots the motor operating regions.

    Args:
        data_obj: MachineData instance generated by ``grid_to_data``.
        title: Figure title.
        machine: Currently unused; kept for API compatibility.
        override_torq_2d: Optional 2D torque grid to use instead of the
            commanded torque mesh (e.g., the achieved/predicted torque).
    """
    colors_map = PlotConfig.get_colors()
    labels_map = PlotConfig.get_labels()

    with plt.rc_context(PlotConfig.get_rc_params()):
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.set_title(title)

        omega_rpm = data_obj.omega
        vec_torq = data_obj.torq

        ax.set_xlabel("Speed [r/min]")
        ax.set_ylabel("Torque [Nm]")

        omega_2d, default_torq_2d = np.meshgrid(omega_rpm, vec_torq)

        # Use the override array if provided, otherwise default to commanded torque
        torq_2d = override_torq_2d if override_torq_2d is not None else default_torq_2d

        modes_valid = data_obj.segments

        valid_mask = ~np.isnan(modes_valid)
        omega_valid = omega_2d[valid_mask]
        torq_valid = torq_2d[valid_mask]
        modes_valid = modes_valid[valid_mask]

        # Use the canonical unique-segments source from MachineData. Cast to int
        # there means we can drop the per-iteration int(seg_val) casts below.
        for seg_val in data_obj.unique_segments:
            mask = modes_valid == seg_val
            color = colors_map.get(seg_val, "black")
            label_name = labels_map.get(seg_val, f"Segment_{seg_val}")

            ax.scatter(
                omega_valid[mask],
                torq_valid[mask],
                s=10,
                c=[color] * mask.sum(),
                marker=".",
                label=label_name,
            )

        PlotConfig.apply_deduplicated_legend(ax)
        ax.grid(True)
        plt.show()


_MODEL_COLORS: dict[str, str] = {"Analytical": "tab:blue", "Neural": "tab:green"}
_DEFAULT_COLOR: str = "tab:gray"


def plot_global_performance(
    df: pd.DataFrame | None,
    machine: BaseMachine,
    models: list[str] | None = None,
    test_mask: np.ndarray | None = None,
) -> None:
    """
    Plots predicted vs. measured torque for one or more models.

    Args:
        df: DataFrame containing ``torq_meas`` and per-model ``torq_<Model>``
            and ``Error_<Model>`` columns.
        machine: Machine instance (currently unused; kept for API compatibility).
        models: Subset of model names to plot. Defaults to all detected
            ``Error_<Model>`` columns.
        test_mask: Boolean array of length ``len(df)`` flagging rows belonging
            to the held-out test set. When provided, train points are drawn
            as hollow markers and test points filled, and the reported RMSE
            is computed on the test slice only. When ``None``, all points are
            drawn identically and the RMSE is computed over the entire
            DataFrame.
    """
    if df is None or df.empty:
        print("Provided DataFrame is empty or None.")
        return

    if models is None:
        models = [
            col.replace("Error_", "") for col in df.columns if col.startswith("Error_")
        ]

    if not models:
        print("No model error columns found.")
        return

    if test_mask is not None:
        test_mask = np.asarray(test_mask, dtype=bool)
        if test_mask.shape != (len(df),):
            raise ValueError(
                f"test_mask shape {test_mask.shape} does not match DataFrame length ({len(df)})."
            )

    n_models = len(models)

    with plt.rc_context(
        PlotConfig.get_rc_params(
            {"axes.labelsize": 16, "xtick.labelsize": 14, "ytick.labelsize": 14}
        )
    ):
        fig, axes = plt.subplots(1, n_models, figsize=(7 * n_models, 5), sharey=True)
        if n_models == 1:
            axes = [axes]

        min_val, max_val = df["torq_meas"].min(), df["torq_meas"].max()

        for i, model in enumerate(models):
            error_col, pred_col = f"Error_{model}", f"torq_{model}"
            if (
                pred_col not in df.columns
                and model == "Analytical"
                and "torq_model" in df.columns
            ):
                pred_col = "torq_model"

            if pred_col not in df.columns:
                continue

            color = _MODEL_COLORS.get(model, _DEFAULT_COLOR)

            if test_mask is None:
                rmse = np.sqrt(np.mean(df[error_col] ** 2))
                axes[i].scatter(
                    df["torq_meas"], df[pred_col], alpha=0.5, s=10, color=color
                )
                axes[i].set_title(f"{model} (RMSE={rmse:.3f})", fontsize=18)
            else:
                rmse_test = np.sqrt(np.mean(df.loc[test_mask, error_col] ** 2))
                # Train: hollow circles
                axes[i].scatter(
                    df.loc[~test_mask, "torq_meas"],
                    df.loc[~test_mask, pred_col],
                    s=30,
                    facecolors="none",
                    edgecolors=color,
                    linewidths=0.8,
                    alpha=0.6,
                    label="Train",
                )
                # Test: filled markers
                axes[i].scatter(
                    df.loc[test_mask, "torq_meas"],
                    df.loc[test_mask, pred_col],
                    s=30,
                    color=color,
                    label=f"Test (RMSE: {rmse_test:.3f})",
                )
                axes[i].legend(loc="upper left", fontsize=14)
                axes[i].set_title(f"{model}", fontsize=18)

            axes[i].plot([min_val, max_val], [min_val, max_val], "r--", lw=2)
            axes[i].set_xlabel("Measured Torque [Nm]")
            axes[i].grid(True, alpha=0.3)

            min_val = min(min_val, df[pred_col].min())
            max_val = max(max_val, df[pred_col].max())

        axes[0].set_ylabel("Predicted Torque [Nm]")
        plt.tight_layout()
        plt.show()


def plot_residual_torque_error(dict_grid: dict[str, Any], machine: BaseMachine) -> None:
    """
    Plots the residual torque error (commanded minus neural-predicted)
    over the (speed, torque) operating plane.
    """
    omega_rpm = dict_grid["vec_omega"] * dict_grid.get(
        "const_mech_speed", 30 / (np.pi * machine.n_ppairs)
    )
    T_target = dict_grid["vec_torq"]

    T_target_2d = np.tile(T_target[:, np.newaxis], (1, len(omega_rpm)))
    T_actual_2d = dict_grid["grid_torq_neural"]

    valid_mask = ~np.isnan(dict_grid["curr_dq_grid"][0])
    T_diff = np.where(valid_mask, T_target_2d - T_actual_2d, np.nan)

    custom_rc = PlotConfig.get_rc_params(
        {"font.size": 24, "axes.labelsize": 26, "axes.titlesize": 26}
    )
    with plt.rc_context(custom_rc):
        PlotConfig.plot_speed_torque_heatmap(
            omega_rpm,
            T_target,
            T_diff,
            valid_mask,
            cbar_label="Residual Torque Error $T_{base} - T_{PAM}$ [Nm]",
            y_label="Predicted Torque [Nm]",
        )


def plot_current_trajectories_split(
    dict_grid_base: dict[str, Any],
    dict_grid_recalc: dict[str, Any],
    machine: BaseMachine,
) -> None:
    """
    Plots the d-q current trajectories for each harmonic subspace, side by
    side for the analytical baseline grid and the neural-recalculated grid.
    """
    colors_map = PlotConfig.get_colors()
    labels_map = PlotConfig.get_labels()

    n_harmonics = (machine.n_phases - 1) // 2

    with plt.rc_context(PlotConfig.get_rc_params({"axes.labelsize": 24})):
        fig, axes = plt.subplots(n_harmonics, 2, figsize=(18, 7 * n_harmonics))
        if n_harmonics == 1:
            axes = np.expand_dims(axes, axis=0)

        def plot_grid_onto_ax(
            ax: Axes, dict_grid: dict[str, Any], d_idx: int, q_idx: int
        ) -> None:
            d_grid, q_grid = (
                dict_grid["curr_dq_grid"][d_idx],
                dict_grid["curr_dq_grid"][q_idx],
            )

            mode_grid = dict_grid.get("grid_segments", np.zeros_like(d_grid))

            valid_mask = ~np.isnan(d_grid)
            d_valid, q_valid, modes_valid = (
                d_grid[valid_mask],
                q_grid[valid_mask],
                mode_grid[valid_mask],
            )

            unique_modes = np.unique(modes_valid[~np.isnan(modes_valid)])
            for mode in unique_modes:
                mask = modes_valid == mode
                ax.scatter(
                    d_valid[mask],
                    q_valid[mask],
                    s=40,
                    alpha=0.5,
                    c=colors_map.get(int(mode), "black"),
                    label=labels_map.get(int(mode), str(int(mode))),
                    marker=".",
                )

            ax.grid(True, alpha=0.3)
            ax.axis("equal")

        for h in range(n_harmonics):
            d_idx, q_idx, h_num = 2 * h, 2 * h + 1, 2 * h + 1
            plot_grid_onto_ax(axes[h, 0], dict_grid_base, d_idx, q_idx)
            plot_grid_onto_ax(axes[h, 1], dict_grid_recalc, d_idx, q_idx)

            axes[h, 0].set_ylabel(f"$i_{{q{h_num}}}$ [A]")
            axes[h, 0].set_xlabel(f"$i_{{d{h_num}}}$ [A]")
            axes[h, 1].set_xlabel(f"$i_{{d{h_num}}}$ [A]")

        PlotConfig.apply_deduplicated_legend(
            fig, loc="center right", bbox_to_anchor=(0.92, 0.5), markerscale=3
        )

        axes[0, 0].set_title("Baseline (Analytical)")
        axes[0, 1].set_title("Recalculated (Neural Optimized)")

        plt.tight_layout()
        plt.subplots_adjust(right=0.90, hspace=0.2, wspace=0.2)
        plt.show()


def plot_joule_losses_reduction(
    dict_grid_base: dict[str, Any],
    dict_grid_recalc: dict[str, Any],
    machine: BaseMachine,
) -> None:
    """
    Plots the Joule losses reduction (baseline minus recalculated) as a heatmap
    over the (speed, torque) plane and prints the maximum savings achieved.
    """
    omega_rpm = dict_grid_recalc["vec_omega"] * dict_grid_recalc.get(
        "const_mech_speed", 30 / (np.pi * machine.n_ppairs)
    )
    vec_torq = dict_grid_recalc["vec_torq"]

    mask_base = ~np.isnan(dict_grid_base["curr_dq_grid"][0])
    mask_recalc = ~np.isnan(dict_grid_recalc["curr_dq_grid"][0])
    common_mask = mask_base & mask_recalc

    if not np.any(common_mask):
        print("No overlapping data points found.")
        return

    R_diag = np.diag(machine.R_stat)

    broadcast_shape = [slice(None)] + [np.newaxis] * (
        dict_grid_base["curr_dq_grid"].ndim - 1
    )
    R_broad = R_diag[tuple(broadcast_shape)]

    P_loss_base = machine.k_phase * np.sum(
        dict_grid_base["curr_dq_grid"] ** 2 * R_broad, axis=0
    )
    P_loss_recalc = machine.k_phase * np.sum(
        dict_grid_recalc["curr_dq_grid"] ** 2 * R_broad, axis=0
    )

    P_diff = np.where(common_mask, P_loss_base - P_loss_recalc, np.nan)

    with plt.rc_context(PlotConfig.get_rc_params()):
        PlotConfig.plot_speed_torque_heatmap(
            omega_rpm,
            vec_torq,
            P_diff,
            common_mask,
            cbar_label="Joule Losses Reduction [Watts]",
            cbar_kwargs={"rotation": 270, "labelpad": 30, "size": 20},
        )

    print(f"Analysis Complete. Max savings: {np.nanmax(P_diff):.2f} W")
