from typing import Any, Literal

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.axes import Axes

from ..parameters import BaseMachine
from ..simulation import MachineData
from .plot_config import PlotConfig


def plot_grid_segments(
    data_obj: MachineData,
    title: str = "Segments Overview",
    machine: BaseMachine | None = None,
    override_torq_2d: np.ndarray | None = None,
    background: MachineData | None = None,
    background_alpha: float = 0.3,
) -> None:
    """
    Plots the motor operating regions.

    Args:
        data_obj: MachineData instance generated by ``grid_to_data``.
        title: Figure title.
        machine: Currently unused; kept for API compatibility.
        override_torq_2d: Optional 2D torque grid to use instead of the
            commanded torque mesh (e.g., the achieved/predicted torque).
        background: Optional second ``MachineData`` instance drawn beneath
            ``data_obj`` at reduced alpha. Typical use: pass the healthy
            grid as background and a fault grid as foreground so the
            shrunken feasible envelope is visible at a glance.
        background_alpha: Opacity for the background scatter; ignored when
            ``background`` is None. Default 0.3 (i.e. 70% see-through).
    """
    colors_map = PlotConfig.get_colors()
    labels_map = PlotConfig.get_labels()

    with plt.rc_context(PlotConfig.get_rc_params()):
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.set_title(title)

        ax.set_xlabel("Speed [r/min]")
        ax.set_ylabel("Torque [Nm]")

        if background is not None:
            _scatter_segments(
                ax=ax,
                data_obj=background,
                colors_map=colors_map,
                labels_map=labels_map,
                alpha=background_alpha,
                include_in_legend=False,
                override_torq_2d=None,
                rasterized=True,
            )

        _scatter_segments(
            ax=ax,
            data_obj=data_obj,
            colors_map=colors_map,
            labels_map=labels_map,
            alpha=1.0,
            include_in_legend=True,
            override_torq_2d=override_torq_2d,
            rasterized=False,
        )

        PlotConfig.apply_deduplicated_legend(ax)
        ax.grid(True)
        plt.show()


def _scatter_segments(
    ax: Axes,
    data_obj: MachineData,
    colors_map: dict[int, str],
    labels_map: dict[int, str],
    alpha: float,
    include_in_legend: bool,
    override_torq_2d: np.ndarray | None,
    rasterized: bool,
) -> None:
    """
    Draws one MachineData's segments onto ``ax``. Helper extracted from
    ``plot_grid_segments`` so the background and foreground passes share
    a single code path.
    """
    omega_rpm = data_obj.omega
    vec_torq = data_obj.torq

    omega_2d, default_torq_2d = np.meshgrid(omega_rpm, vec_torq)
    torq_2d = override_torq_2d if override_torq_2d is not None else default_torq_2d

    modes_valid = data_obj.segments
    valid_mask = ~np.isnan(modes_valid)
    omega_valid = omega_2d[valid_mask]
    torq_valid = torq_2d[valid_mask]
    modes_valid = modes_valid[valid_mask]

    for seg_val in data_obj.unique_segments:
        mask = modes_valid == seg_val
        color = colors_map.get(seg_val, "black")
        label_name = labels_map.get(seg_val, f"Segment_{seg_val}") if include_in_legend else None

        ax.scatter(
            omega_valid[mask],
            torq_valid[mask],
            s=10,
            c=[color] * mask.sum(),
            marker=".",
            alpha=alpha,
            label=label_name,
            rasterized=rasterized,
        )


_MODEL_COLORS: dict[str, str] = {"Analytical": "tab:blue", "Neural": "tab:green"}
_DEFAULT_COLOR: str = "tab:gray"


def plot_global_performance(
    df: pd.DataFrame | None,
    machine: BaseMachine,
    models: list[str] | None = None,
    test_mask: np.ndarray | None = None,
) -> None:
    """
    Plots predicted vs. measured torque for one or more models.

    Args:
        df: DataFrame containing ``torq_meas`` and per-model ``torq_<Model>``
            and ``Error_<Model>`` columns.
        machine: Machine instance (currently unused; kept for API compatibility).
        models: Subset of model names to plot. Defaults to all detected
            ``Error_<Model>`` columns.
        test_mask: Boolean array of length ``len(df)`` flagging rows belonging
            to the held-out test set. When provided, train points are drawn
            as hollow markers and test points filled, and the reported RMSE
            is computed on the test slice only. When ``None``, all points are
            drawn identically and the RMSE is computed over the entire
            DataFrame.
    """
    if df is None or df.empty:
        print("Provided DataFrame is empty or None.")
        return

    if models is None:
        models = [col.replace("Error_", "") for col in df.columns if col.startswith("Error_")]

    if not models:
        print("No model error columns found.")
        return

    if test_mask is not None:
        test_mask = np.asarray(test_mask, dtype=bool)
        if test_mask.shape != (len(df),):
            raise ValueError(f"test_mask shape {test_mask.shape} does not match DataFrame length ({len(df)}).")

    n_models = len(models)

    with plt.rc_context(PlotConfig.get_rc_params({"axes.labelsize": 16, "xtick.labelsize": 14, "ytick.labelsize": 14})):
        fig, axes = plt.subplots(1, n_models, figsize=(7 * n_models, 5), sharey=True)
        if n_models == 1:
            axes = [axes]

        min_val, max_val = df["torq_meas"].min(), df["torq_meas"].max()

        for i, model in enumerate(models):
            error_col, pred_col = f"Error_{model}", f"torq_{model}"
            if pred_col not in df.columns and model == "Analytical" and "torq_model" in df.columns:
                pred_col = "torq_model"

            if pred_col not in df.columns:
                continue

            color = _MODEL_COLORS.get(model, _DEFAULT_COLOR)

            if test_mask is None:
                rmse = np.sqrt(np.mean(df[error_col] ** 2))
                axes[i].scatter(df["torq_meas"], df[pred_col], alpha=0.5, s=10, color=color)
                axes[i].set_title(f"{model} (RMSE={rmse:.3f})", fontsize=18)
            else:
                rmse_test = np.sqrt(np.mean(df.loc[test_mask, error_col] ** 2))
                # Train: hollow circles
                axes[i].scatter(
                    df.loc[~test_mask, "torq_meas"],
                    df.loc[~test_mask, pred_col],
                    s=30,
                    facecolors="none",
                    edgecolors=color,
                    linewidths=0.8,
                    alpha=0.6,
                    label="Train",
                )
                # Test: filled markers
                axes[i].scatter(
                    df.loc[test_mask, "torq_meas"],
                    df.loc[test_mask, pred_col],
                    s=30,
                    color=color,
                    label=f"Test (RMSE: {rmse_test:.3f})",
                )
                axes[i].legend(loc="upper left", fontsize=14)
                axes[i].set_title(f"{model}", fontsize=18)

            axes[i].plot([min_val, max_val], [min_val, max_val], "r--", lw=2)
            axes[i].set_xlabel("Measured Torque [Nm]")
            axes[i].grid(True, alpha=0.3)

            min_val = min(min_val, df[pred_col].min())
            max_val = max(max_val, df[pred_col].max())

        axes[0].set_ylabel("Predicted Torque [Nm]")
        plt.tight_layout()
        plt.show()


def plot_residual_torque_error(dict_grid: dict[str, Any], machine: BaseMachine) -> None:
    """
    Plots the residual torque error (commanded minus neural-predicted) on the
    correction grid. Each cell is positioned at its achieved (neural-predicted)
    torque rather than at the commanded torque value.
    """
    omega_rpm = dict_grid["vec_omega"] * dict_grid.get("const_mech_speed", 30 / (np.pi * machine.n_ppairs))
    T_target = dict_grid["vec_torq"]
    T_actual_2d = dict_grid["grid_torq_neural"]
    T_target_2d = np.tile(T_target[:, np.newaxis], (1, len(omega_rpm)))

    valid_mask = ~np.isnan(dict_grid["curr_dq_grid"][0]) & ~np.isnan(T_actual_2d)
    T_diff = T_target_2d - T_actual_2d

    omega_2d, _ = np.meshgrid(omega_rpm, T_target)

    custom_rc = PlotConfig.get_rc_params({"font.size": 24, "axes.labelsize": 26, "axes.titlesize": 26})
    with plt.rc_context(custom_rc):
        fig, ax = plt.subplots(figsize=(14, 9))
        sc = ax.scatter(
            omega_2d[valid_mask],
            T_actual_2d[valid_mask],
            c=T_diff[valid_mask],
            cmap="Reds",
            s=40,
            marker="s",
            linewidths=0,
        )
        cbar = fig.colorbar(sc, ax=ax)
        cbar.set_label("Residual Torque Error $T_{base} - T_{PAM}$ [Nm]", size=24, labelpad=20)
        ax.set_xlabel("Speed [r/min]", labelpad=10)
        ax.set_ylabel("Achieved Torque [Nm]", labelpad=10)
        ax.grid(True, which="both", linestyle="-", alpha=0.4)
        plt.tight_layout()
        plt.show()


def plot_current_trajectories(
    grids_by_label: dict[str, dict[str, Any]],
    machine: BaseMachine,
    orientation: Literal["horizontal", "vertical"] = "horizontal",
    figsize: tuple[float, float] | None = None,
) -> None:
    """
    Plots d-q current trajectories for one or more grids across every
    harmonic subspace the machine supports.

    Layout depends on ``orientation``:
        - "horizontal": grids laid out side by side. Subplot grid is
          ``(n_harmonics, n_grids)`` — harmonics stacked in rows, grids
          arranged in columns. Each column gets the grid label as a
          column title; the leftmost column carries the ``$i_q$`` ylabel.
          This is the original baseline-vs-recalculated view.
        - "vertical": grids stacked on top of each other. Subplot grid is
          ``(n_grids, n_harmonics)`` — grids in rows, harmonics in columns.
          Each column's top axis gets a harmonic title; the leftmost
          column carries the grid label (replacing ``$i_q$``, which is
          implied by the d-q convention). Bottom row gets ``$i_d$`` xlabels.

    Args:
        grids_by_label: Ordered mapping of display name -> grid dict.
            Insertion order determines plot order.
        machine: The machine instance; only ``n_phases`` is consulted, to
            derive the number of harmonic subspaces.
        orientation: ``"horizontal"`` or ``"vertical"``. See above.
        figsize: Explicit figure size; if ``None``, a sensible default is
            chosen based on the layout (~9x7 per cell for horizontal,
            ~8x6 per cell for vertical).
    """
    if not grids_by_label:
        raise ValueError("grids_by_label must contain at least one grid.")
    if orientation not in ("horizontal", "vertical"):
        raise ValueError(f"orientation must be 'horizontal' or 'vertical'; got {orientation!r}.")

    colors_map = PlotConfig.get_colors()
    labels_map = PlotConfig.get_labels()

    labels = list(grids_by_label.keys())
    grids = list(grids_by_label.values())
    n_grids = len(grids)
    n_harmonics = (machine.n_phases - 1) // 2
    harmonic_numbers = [2 * h + 1 for h in range(n_harmonics)]

    if orientation == "horizontal":
        nrows, ncols = n_harmonics, n_grids
        default_figsize = (9 * ncols, 7 * nrows)
    else:
        nrows, ncols = n_grids, n_harmonics
        default_figsize = (8 * ncols, 6 * nrows)
    figsize = figsize or default_figsize

    with plt.rc_context(PlotConfig.get_rc_params({"axes.labelsize": 24})):
        fig, axes = plt.subplots(nrows, ncols, figsize=figsize)
        axes = _ensure_axes_2d(axes, nrows, ncols)

        for i in range(nrows):
            for j in range(ncols):
                if orientation == "horizontal":
                    grid = grids[j]
                    h_num = harmonic_numbers[i]
                else:
                    grid = grids[i]
                    h_num = harmonic_numbers[j]

                d_idx, q_idx = h_num - 1, h_num  # 1->(0,1), 3->(2,3), 5->(4,5), ...
                _plot_dq_scatter_onto_ax(
                    ax=axes[i, j],
                    dict_grid=grid,
                    d_idx=d_idx,
                    q_idx=q_idx,
                    colors_map=colors_map,
                    labels_map=labels_map,
                )

        if orientation == "horizontal":
            for j, label in enumerate(labels):
                axes[0, j].set_title(label)
            for i, h_num in enumerate(harmonic_numbers):
                axes[i, 0].set_ylabel(f"$i_{{q{h_num}}}$ [A]")
                for j in range(ncols):
                    axes[i, j].set_xlabel(f"$i_{{d{h_num}}}$ [A]")
        else:
            for j, h_num in enumerate(harmonic_numbers):
                axes[0, j].set_title(f"Harmonic $h = {h_num}$")
            for i in range(nrows):
                for j, h_num in enumerate(harmonic_numbers):
                    axes[i, j].set_xlabel(f"$i_{{d{h_num}}}$ [A]")
                    axes[i, j].set_ylabel(f"$i_{{q{h_num}}}$ [A]")

        PlotConfig.apply_deduplicated_legend(fig, loc="center right", bbox_to_anchor=(0.92, 0.5), markerscale=3)

        plt.tight_layout()
        plt.subplots_adjust(right=0.90, hspace=0.2, wspace=0.2)

        if orientation == "vertical":
            plt.subplots_adjust(left=0.11)
            for i, label in enumerate(labels):
                bbox = axes[i, 0].get_position()
                fig.text(
                    0.02,
                    (bbox.y0 + bbox.y1) / 2,
                    label,
                    rotation=90,
                    ha="center",
                    va="center",
                    fontsize=22,
                    fontweight="bold",
                )

        plt.show()


def plot_current_trajectories_split(
    dict_grid_base: dict[str, Any],
    dict_grid_recalc: dict[str, Any],
    machine: BaseMachine,
) -> None:
    """
    Convenience wrapper preserving the original baseline-vs-recalculated
    view. Equivalent to ``plot_current_trajectories`` with two grids and
    horizontal orientation; kept as a separate function for backward
    compatibility with existing notebooks.
    """
    plot_current_trajectories(
        grids_by_label={
            "Baseline (Analytical)": dict_grid_base,
            "Recalculated (Neural Optimized)": dict_grid_recalc,
        },
        machine=machine,
        orientation="horizontal",
    )


def _ensure_axes_2d(axes: Any, nrows: int, ncols: int) -> np.ndarray:
    """
    Coerces ``plt.subplots`` output into a 2D ``np.ndarray`` regardless of
    whether ``nrows`` or ``ncols`` was 1.
    """
    if nrows == 1 and ncols == 1:
        return np.array([[axes]])
    if nrows == 1:
        return np.asarray(axes)[np.newaxis, :]
    if ncols == 1:
        return np.asarray(axes)[:, np.newaxis]
    return np.asarray(axes)


def _plot_dq_scatter_onto_ax(
    ax: Axes,
    dict_grid: dict[str, Any],
    d_idx: int,
    q_idx: int,
    colors_map: dict[int, str],
    labels_map: dict[int, str],
) -> None:
    """
    Scatters one grid's d-q current trajectory for one harmonic onto one
    axis, coloured by operating-regime segment. Shared by both the
    horizontal and vertical layouts.
    """
    d_grid = dict_grid["curr_dq_grid"][d_idx]
    q_grid = dict_grid["curr_dq_grid"][q_idx]

    mode_grid = dict_grid.get("grid_segments", np.zeros_like(d_grid))

    valid_mask = ~np.isnan(d_grid)
    d_valid, q_valid, modes_valid = (
        d_grid[valid_mask],
        q_grid[valid_mask],
        mode_grid[valid_mask],
    )

    unique_modes = np.unique(modes_valid[~np.isnan(modes_valid)])
    for mode in unique_modes:
        mask = modes_valid == mode
        ax.scatter(
            d_valid[mask],
            q_valid[mask],
            s=40,
            alpha=0.5,
            c=colors_map.get(int(mode), "black"),
            label=labels_map.get(int(mode), str(int(mode))),
            marker=".",
        )

    ax.grid(True, alpha=0.3)
    ax.axis("equal")


def plot_joule_losses_reduction(
    dict_grid_base: dict[str, Any],
    dict_grid_recalc: dict[str, Any],
    machine: BaseMachine,
) -> None:
    """
    Plots the Joule losses reduction (baseline minus recalculated) as a
    heatmap over the (speed, achieved-torque) plane. Each cell is positioned
    at its neural-predicted (achieved) torque from ``dict_grid_recalc``,
    matching the y-axis convention used by the other achieved-torque plots.
    Prints the maximum savings achieved.

    Args:
        dict_grid_base: Baseline grid (analytical optimum).
        dict_grid_recalc: Recalculated grid (neural-optimized currents);
            also provides ``grid_torq_neural`` as the per-cell y-coordinate.
        machine: Machine instance (used for the speed-axis conversion).
    """
    omega_rpm = dict_grid_recalc["vec_omega"] * dict_grid_recalc.get(
        "const_mech_speed", 30 / (np.pi * machine.n_ppairs)
    )
    vec_torq = dict_grid_recalc["vec_torq"]
    T_actual_2d = dict_grid_recalc["grid_torq_neural"]

    mask_base = ~np.isnan(dict_grid_base["curr_dq_grid"][0])
    mask_recalc = ~np.isnan(dict_grid_recalc["curr_dq_grid"][0])
    common_mask = mask_base & mask_recalc & ~np.isnan(T_actual_2d)

    if not np.any(common_mask):
        print("No overlapping data points found.")
        return

    R_diag = np.diag(machine.R_stat)

    broadcast_shape = [slice(None)] + [np.newaxis] * (dict_grid_base["curr_dq_grid"].ndim - 1)
    R_broad = R_diag[tuple(broadcast_shape)]

    P_loss_base = machine.k_phase * np.sum(dict_grid_base["curr_dq_grid"] ** 2 * R_broad, axis=0)
    P_loss_recalc = machine.k_phase * np.sum(dict_grid_recalc["curr_dq_grid"] ** 2 * R_broad, axis=0)

    P_diff = P_loss_base - P_loss_recalc
    omega_2d, _ = np.meshgrid(omega_rpm, vec_torq)

    with plt.rc_context(PlotConfig.get_rc_params()):
        fig, ax = plt.subplots(figsize=(14, 9))
        sc = ax.scatter(
            omega_2d[common_mask],
            T_actual_2d[common_mask],
            c=P_diff[common_mask],
            cmap="Reds",
            s=40,
            marker="s",
            linewidths=0,
        )
        cbar = fig.colorbar(sc, ax=ax)
        cbar.set_label("Joule Losses Reduction [Watts]", rotation=270, labelpad=30, size=20)
        ax.set_xlabel("Speed [r/min]", labelpad=10)
        ax.set_ylabel("Achieved Torque [Nm]", labelpad=10)
        ax.grid(True, which="both", linestyle="-", alpha=0.4)
        plt.tight_layout()
        plt.show()

    print(f"Analysis Complete. Max savings: {np.nanmax(P_diff[common_mask]):.2f} W")
